
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="Supplementaries Team License v1.1"

issueTrackerURL="https://github.com/MehVahdJukaar/StoneZone/issues" #optional

[[mods]] #mandatory

modId="stonezone" #mandatory

version = "${version}"

displayName="Stone Zone" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/stone-zone" #optional

logoFile="logo.png" #optional

credits="" #optional

authors="MehVahdJukaar, Xel'Bayria" #optional

description='''Ultimate Stone Compat Mod'''

itemIcon="stonezone:all_stones" #catalogue icon


[[dependencies.stonezone]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41.0.100,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.stonezone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21]"
    ordering="NONE"
    side="BOTH"

[[dependencies.stonezone]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.15.7,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.stonezone]]
    modId="everycomp"
    mandatory=false
    versionRange="[1.20-2.8.14,]"
    ordering="AFTER"
    side="BOTH"

