name: Report Bug
description: Stone Zone got a bug? Report it.
title: "[🐞]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        BUG

  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: "Code of Conduct"
      options:
        - label: "Always check you are using the latest version of the mods and its dependencies"
          required: true
        - label: "Ensure the version of EveryCompat & Moonlight Lib are up to date"
          required: true
        - label: "Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists."
          required: true
        - label: "If you are unsure which mod is the culprit.\nDisable all of your mods and enable them 1-2 mods each time to isolate the culprit"
          required: true
        - label: "Confirm that there is no existing issue with a similar description submitted in the list of issues."
          required: true

  - type: dropdown
    id: version-loader
    attributes:
      label: "Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)"
      description: "What's the Minecraft version & loader"
      options:
        - DO NOT FORGET the selected one is correct
        - 1.21.1 - FABRIC
        - 1.20.1 - FABRIC
        - 1.21.1 - NEOFORGE
        - 1.20.1 - FORGE
      default: 0
    validations:
      required: true

  - type: input
    id: stonezone
    attributes:
      label: StoneZone Version
      description: The current version of StoneZone
      placeholder: ex. stonezone-1.20-2.7.0
    validations:
      required: true

  - type: input
    id: everycomp
    attributes:
      label: EveryCompat Version
      description: The current version of EveryCompat
      placeholder: ex. everycomp-1.20-2.8.0-forge
    validations:
      required: true
     
  - type: input
    id: moonlight
    attributes:
      label: Moonlight Lib Version
      description: The current version of Moonlight Lib
      placeholder: ex. moonlight-1.20-2.8.46-forge
    validations:
      required: true

  - type: textarea
    id: issue-with-mods
    attributes:
      label: "Issue with mods"
      description: "Which mods does Stone Zone have an issue with?"
      placeholder: "ex. - Strata <version> \nex. - Chipped <version> \n\nStrata is StoneTypes Mod & Create is a Furniture Mod"
    validations:
      required: true

  - type: textarea
    id: issue-details
    attributes:
      label: "Issue Detail"
      description: "A clear and concise description of what the bug is."
      placeholder: "ATTENTION: DO NOT put log files here. The next area (below) is for attaching the log files\nHere is for describing the bug you encountered.\nYou can attach images here."
    validations:
        required: true

  - type: textarea
    attributes:
      label: "OPTIONAL: Latest.log | Crash-report Attachment"
      description: |
        If your Minecraft crashes, it creates a crash-report file which is located in ~/.minecraft/crash-report/
      placeholder: Attach log files (latest.log or crash-report) here by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: textarea
    id: to-reproduce
    attributes:
      label: "OPTIONAL: To Produce"
      description: "Steps to reproduce the behaviour"
      placeholder: "Example:\n1) Place a <block> anywhere\n2) Interact with <block>\n3) The bug happened here"
    validations:
        required: false
