architectury {
    common(enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.mod_id
            from components.java
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.output_directory=${new File(rootProject.buildDir, "docsOut")}")
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.multi_source=true")

    it.options.compilerArgs << "-Xmaxerrs" << "4000"

}

dependencies {

    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"


//!! MOONLIGHT LIB (REQUIRED)  -------------------------------------------------------------------------------------- \\
    String path = System.getenv('REPOS21_1')

    if (enable_moonlight_test.toBoolean()) {
        //- LOCAL
        modImplementation(files(path + "\\Moonlight\\fabric\\build\\libs\\moonlight-$moonlight_testVersion-fabric.jar"))
    }
    else {
        //+ MAVEN
        modApi("net.mehvahdjukaar:moonlight:$moonlight_version"){
            transitive = false
        }
    }

//!! EVERY COMPAT (REQUIRED) ---------------------------------------------------------------------------------------- \\
    if (enable_everycomp_test.toBoolean())
    //- LOCAL
        modImplementation(files(path + "\\WoodGood\\fabric\\build\\libs\\everycomp-$everycomp_testVersion-fabric.jar"))
    else
    //+ MAVEN
        modApi("net.mehvahdjukaar:everycomp:$everycomp_version") {
            transitive = false
        }

//!! ================================================= DEPENDENCIES ================================================= \\

    //+ REQUIRED - The modules access libaries from below
//    modCompileOnly("curse.maven:zeta-968868:5597406") // v1.0.24 | Quark //!! 1.20
    modCompileOnly("curse.maven:owo-lib-532610:6446006") // v0.12.15.4 | Fabric-Waystones

        //+ OTHER MAVENS
    modCompileOnly("org.violetmoon.zeta:Zeta:1.1-39-SNAPSHOT") // Quark - Get correct version @ https://maven.blamejared.com/org/violetmoon/zeta/Zeta/

//!! =================================================== IMPORTS ==================================================== \\
    //- MODULES - don't need library from the mod, so it's fine to ignore

    // ~/common/mods LOCAL

    //+ REQUIRED - The modules access libaries from below
    modCompileOnly("curse.maven:better-archeology-835687:6423003") // Supermartijn642s' Config-Lib, Yung's API
    modCompileOnly("curse.maven:blockus-312289:5896309") //!! 1.20
    modCompileOnly("curse.maven:building-but-better-989479:5382599") //!! 1.20
    modCompileOnly("curse.maven:create-fabric-624165:5982726") //!! 1.20
    modCompileOnly("curse.maven:decorative-blocks-362528:5089408") //!! 1.20
    modCompileOnly("curse.maven:fabric-waystones-410902:5798771")
    modCompileOnly("curse.maven:handcrafted-538214:6330032") // Resourceful-Lib
    modCompileOnly("curse.maven:lets-do-candlelight-farm-charm-compat-1038117:6963399") //MAIN +[Let's-Do]-Farm-&-Charm
    modCompileOnly("curse.maven:lets-do-farm-charm-1038103:6962195") // Architectury-API
    modCompileOnly("curse.maven:more-beautiful-torches-860325:5263631") // MonoLib //!! 1.20
    modCompileOnly("curse.maven:stoneworks-852663:5731745")
    modCompileOnly("curse.maven:twigs-496913:4603805") //!! 1.20
    modCompileOnly("curse.maven:waystones-245755:6856570") // Balm

        //+ OTHER MAVENS
    modCompileOnly("earth.terrarium.chipped:chipped-fabric-1.21.1:4.0.2") //INCLUDED: Athena, Resourceful-Lib
    modCompileOnly("org.violetmoon.quark:Quark:4.1-473-SNAPSHOT") // Zeta - Get correct version @ https://maven.blamejared.com/org/violetmoon/quark/Quark/
}
